Add checking whole workspace

diff --git a/.github/workflows/test-inputs.yml b/.github/workflows/test-inputs.yml
--- a/.github/workflows/test-inputs.yml
+++ b/.github/workflows/test-inputs.yml
@@ -29,15 +29,24 @@ jobs:
         run: |
           cd ref_slice
           git checkout patch_change
-      - name: Run the action
+      - name: Run the action on ref_slice patch change
         uses: ./action/
         with:
           package: ref_slice
+      - name: Run the action on whole workspace (allowed to fail)
+        id: action_all
+        uses: ./action/
+        continue-on-error: true
+      - name: Fail if the action has not returned any errors (but it should have)
+        if: steps.action_all.outcome != 'failure'
+        run: |
+          echo "Error! The action should have failed because of checking the dummy crate, but it has not!"
+          exit 1
       - name: Checkout the test with major change and patch version bump
         run: |
           cd ref_slice
           git checkout major_change
-      - name: Run the action (allowed to fail)
+      - name: Run the action on ref_slice major change (allowed to fail)
         id: action_major
         uses: ./action/
         with:
