Add test-manifest-path

diff --git a/.github/workflows/test-inputs.yml b/.github/workflows/test-inputs.yml
--- a/.github/workflows/test-inputs.yml
+++ b/.github/workflows/test-inputs.yml
@@ -33,7 +33,7 @@ jobs:
         uses: ./action/
         with:
           package: ref_slice
-      - name: Run the action on whole workspace (allowed to fail)
+      - name: Run the action on the whole workspace (allowed to fail)
         id: action_all
         uses: ./action/
         continue-on-error: true
@@ -78,6 +78,66 @@ jobs:
         uses: ./action/
         with:
           verbose: true
+
+  test-manifest-path:
+    name: Test input manifest-path
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the action
+        uses: actions/checkout@v3
+        with:
+          path: action
+      - name: Setup the workspace
+        uses: ./action/.github/workflows/setup-test-workspace
+      - name: Checkout the test with patch change and patch version bump
+        run: |
+          cd ref_slice
+          git checkout patch_change
+      - name: Run the action on ref_slice patch change (Cargo.toml path)
+        uses: ./action/
+        with:
+          manifest-path: ref_slice/Cargo.toml
+      - name: Run the action on ref_slice patch change (crate path)
+        uses: ./action/
+        with:
+          manifest-path: ref_slice
+      - name: Run the action on the whole workspace (Cargo.toml path, allowed to fail)
+        id: action_all_cargo_toml
+        uses: ./action/
+        with:
+          manifest-path: ./Cargo.toml
+        continue-on-error: true
+      - name: Fail if the action has not returned any errors (but it should have)
+        if: steps.action_all_cargo_toml.outcome != 'failure'
+        run: |
+          echo "Error! The action should have failed because of checking the dummy crate, but it has not!"
+          exit 1
+      - name: Checkout the test with major change and patch version bump
+        run: |
+          cd ref_slice
+          git checkout major_change
+      - name: Run the action on ref_slice major change (Cargo.toml path, allowed to fail)
+        id: action_major_cargo_toml
+        uses: ./action/
+        with:
+          manifest-path: ref_slice/Cargo.toml
+        continue-on-error: true
+      - name: Fail if the action has not returned any errors (but it should have)
+        if: steps.action_major_cargo_toml.outcome != 'failure'
+        run: |
+          echo "Error! The action should have failed because of the breaking change, but it has not."
+          exit 1
+      - name: Run the action on ref_slice major change (crate path, allowed to fail)
+        id: action_major_crate
+        uses: ./action/
+        with:
+          manifest-path: ref_slice
+        continue-on-error: true
+      - name: Fail if the action has not returned any errors (but it should have)
+        if: steps.action_major_crate.outcome != 'failure'
+        run: |
+          echo "Error! The action should have failed because of the breaking change, but it has not."
+          exit 1
 
   test-manifest-path-with-space:
     name: Test input manifest-path against path containing space
