Refinement, test-package

diff --git a/.github/workflows/test-inputs.yml b/.github/workflows/test-inputs.yml
--- a/.github/workflows/test-inputs.yml
+++ b/.github/workflows/test-inputs.yml
@@ -1,5 +1,12 @@
 name: Test action inputs
 
+# Assumes that the latest published normal version of `ref_slice` smaller
+# than 1.2.2 is 1.2.1.
+# TODO: Change the crate version in the corresponding branches `patch_change`
+# and `major_change` to 1.2.1 once new logic of choosing baseline is adapted.
+# Otherwise if new version 1.2.2 of `ref_slice` is released, the tests might
+# stop working correctly.
+
 on:
   workflow_call:
 
@@ -8,8 +15,42 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  test-manifest-path:
-    name: Test input manifest-path
+  test-package:
+    name: Test input package
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup the workspace
+        uses: ./.github/workflows/setup-test-workspace.yml
+      - name: Checkout the action
+        uses: actions/checkout@v3
+        with:
+          path: action
+      - name: Checkout the test with patch change and patch version bump
+        run: |
+          cd ref_slice
+          git checkout patch_change
+      - name: Run the action
+        uses: ./action/
+        with:
+          package: ref_slice
+      - name: Checkout the test with major change and patch version bump
+        run: |
+          cd ref_slice
+          git checkout major_change
+      - name: Run the action (allowed to fail)
+        id: action_major
+        uses: ./action/
+        with:
+          package: ref_slice
+        continue-on-error: true
+      - name: Fail if the action has not returned any errors (but it should have)
+        if: steps.action_major.outcome != 'failure'
+        run: |
+          echo "Error! The action should have failed because of the breaking change, but it has not."
+          exit 1
+
+  test-manifest-path-with-space:
+    name: Test input manifest-path against path containing space
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the test repository
@@ -25,12 +66,6 @@ jobs:
         uses: actions/checkout@v3
         with:
           path: action
-      # Assumes that the latest published normal version of `ref_slice` smaller
-      # than 1.2.2 is 1.2.1.
-      # TODO: Change the crate version in the corresponding branch `patch_change`
-      # to 1.2.1 once new logic of choosing baseline is adapted. Otherwise
-      # if new version 1.2.2 of `ref_slice` is released, the tests might stop
-      # working correctly.
       - name: Checkout the test with patch change and patch version bump
         run: |
           cd "ref slice"
@@ -39,12 +74,6 @@ jobs:
         uses: ./action/
         with:
           manifest-path: 'ref slice/Cargo.toml'
-      # Assumes that the latest published normal version of `ref_slice` smaller
-      # than 1.2.2 exports a public function `ref_slice`.
-      # TODO: Change the crate version in the corresponding branch `major_change`
-      # to 1.2.1 once new logic of choosing baseline is adapted. Otherwise
-      # if new version 1.2.2 of `ref_slice` is released, the tests might stop
-      # working correctly.
       - name: Checkout the test with major change and patch version bump
         run: |
           cd "ref slice"
@@ -54,60 +83,6 @@ jobs:
         uses: ./action/
         with:
           manifest-path: 'ref slice/Cargo.toml'
-        continue-on-error: true
-      - name: Fail if the action has not returned any errors (but it should have)
-        if: steps.action_major.outcome != 'failure'
-        run: |
-          echo "Error! The action should have failed because of the breaking change, but it has not."
-          exit 1
-
-  test-package:
-    name: Test input package
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        package: [ref_slice]
-    steps:
-      - name: Checkout the test repository
-        uses: actions/checkout@v3
-        with:
-          path: 'ref_slice'
-          repository: mgr0dzicki/cargo-semver-action-ref-slice
-          fetch-depth: 0
-          persist-credentials: true
-      - name: Checkout the action
-        uses: actions/checkout@v3
-        with:
-          path: action
-      # Assumes that the latest published normal version of `ref_slice` smaller
-      # than 1.2.2 is 1.2.1.
-      # TODO: Change the crate version in the corresponding branch `patch_change`
-      # to 1.2.1 once new logic of choosing baseline is adapted. Otherwise
-      # if new version 1.2.2 of `ref_slice` is released, the tests might stop
-      # working correctly.
-      - name: Checkout the test with patch change and patch version bump
-        run: |
-          cd ref_slice
-          git checkout patch_change
-      - name: Run the action
-        uses: ./action/
-        with:
-          package: ${{ matrix.package }}
-      # Assumes that the latest published normal version of `ref_slice` smaller
-      # than 1.2.2 exports a public function `ref_slice`.
-      # TODO: Change the crate version in the corresponding branch `major_change`
-      # to 1.2.1 once new logic of choosing baseline is adapted. Otherwise
-      # if new version 1.2.2 of `ref_slice` is released, the tests might stop
-      # working correctly.
-      - name: Checkout the test with major change and patch version bump
-        run: |
-          cd ref_slice
-          git checkout major_change
-      - name: Run the action (allowed to fail)
-        id: action_major
-        uses: ./action/
-        with:
-          package: ${{ matrix.package }}
         continue-on-error: true
       - name: Fail if the action has not returned any errors (but it should have)
         if: steps.action_major.outcome != 'failure'
